// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlms0hr2REMeA_a6Rn-yKT2LJWiJZIoaI',
    appId: '1:447825170642:web:6f9be884f928e10bc15d0b',
    messagingSenderId: '447825170642',
    projectId: 'smartagricultureapp-718ca',
    authDomain: 'smartagricultureapp-718ca.firebaseapp.com',
    storageBucket: 'smartagricultureapp-718ca.firebasestorage.app',
    measurementId: 'G-DQPDF3ZD4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa-ENdPzL64j9romtKmsfXbTkQmw4xXSI',
    appId: '1:447825170642:android:8a5c5a376b10c0c6c15d0b',
    messagingSenderId: '447825170642',
    projectId: 'smartagricultureapp-718ca',
    storageBucket: 'smartagricultureapp-718ca.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlms0hr2REMeA_a6Rn-yKT2LJWiJZIoaI',
    appId: '1:447825170642:web:8dbf7ac09d696a55c15d0b',
    messagingSenderId: '447825170642',
    projectId: 'smartagricultureapp-718ca',
    authDomain: 'smartagricultureapp-718ca.firebaseapp.com',
    storageBucket: 'smartagricultureapp-718ca.firebasestorage.app',
    measurementId: 'G-WH8NXSBEFJ',
  );
}
