class DummyData {
  static final List<Map<String, dynamic>> cropData = [
    {
      "name": "Wheat",
      "nameHindi": "गेहूं",
      "season": ["Rabi"],
      "soilType": ["Loamy"],
      "waterRequirement": "Medium",
      "temperatureRange": "10-25°C",
      "growthDurationDays": 120,
      "fertilizer": "Nitrogen rich",
      "region": ["Punjab", "UP"],
      "pricePerQuintal": 2200,
      "description": "Wheat is a staple food crop grown in winter season.",
      "imageUrl": "https://picsum.photos/200?1",
      "searchKeywords": ["wheat", "gehun"]
    },
    {
      "name": "Rice",
      "nameHindi": "धान",
      "season": ["Kharif"],
      "soilType": ["Clay"],
      "waterRequirement": "High",
      "temperatureRange": "20-35°C",
      "growthDurationDays": 150,
      "fertilizer": "Urea",
      "region": ["West Bengal", "Bihar"],
      "pricePerQuintal": 2100,
      "description": "Rice requires high water and is grown in flooded fields.",
      "imageUrl": "https://picsum.photos/200?2",
      "searchKeywords": ["rice", "dhan"]
    },
    {
      "name": "Maize",
      "nameHindi": "मक्का",
      "season": ["Kharif", "Rabi"],
      "soilType": ["Loamy"],
      "waterRequirement": "Medium",
      "temperatureRange": "18-27°C",
      "growthDurationDays": 90,
      "fertilizer": "Compost",
      "region": ["MP", "Karnataka"],
      "pricePerQuintal": 1800,
      "description": "Maize is used for food as well as animal feed.",
      "imageUrl": "https://picsum.photos/200?3",
      "searchKeywords": ["maize", "makka"]
    },
    {
      "name": "Sugarcane",
      "nameHindi": "गन्ना",
      "season": ["Annual"],
      "soilType": ["Loamy"],
      "waterRequirement": "High",
      "temperatureRange": "20-30°C",
      "growthDurationDays": 300,
      "fertilizer": "Organic manure",
      "region": ["UP", "Maharashtra"],
      "pricePerQuintal": 350,
      "description": "Sugarcane is used to produce sugar and jaggery.",
      "imageUrl": "https://picsum.photos/200?4",
      "searchKeywords": ["sugarcane", "ganna"]
    },
    {
      "name": "Potato",
      "nameHindi": "आलू",
      "season": ["Rabi"],
      "soilType": ["Sandy"],
      "waterRequirement": "Medium",
      "temperatureRange": "15-20°C",
      "growthDurationDays": 90,
      "fertilizer": "Potassium rich",
      "region": ["UP", "Bihar"],
      "pricePerQuintal": 1200,
      "description": "Potato is a widely consumed vegetable crop.",
      "imageUrl": "https://picsum.photos/200?5",
      "searchKeywords": ["potato", "aloo"]
    },
    {
      "name": "Tomato",
      "nameHindi": "टमाटर",
      "season": ["All"],
      "soilType": ["Loamy"],
      "waterRequirement": "Medium",
      "temperatureRange": "18-30°C",
      "growthDurationDays": 80,
      "fertilizer": "Compost",
      "region": ["Karnataka", "Andhra"],
      "pricePerQuintal": 1500,
      "description": "Tomato is used in cooking and sauces.",
      "imageUrl": "https://picsum.photos/200?6",
      "searchKeywords": ["tomato"]
    },
    {
      "name": "Onion",
      "nameHindi": "प्याज",
      "season": ["Rabi"],
      "soilType": ["Sandy"],
      "waterRequirement": "Low",
      "temperatureRange": "13-24°C",
      "growthDurationDays": 100,
      "fertilizer": "Sulfur rich",
      "region": ["Maharashtra"],
      "pricePerQuintal": 1400,
      "description": "Onion is used in almost all Indian dishes.",
      "imageUrl": "https://picsum.photos/200?7",
      "searchKeywords": ["onion", "pyaj"]
    },
    {
      "name": "Mustard",
      "nameHindi": "सरसों",
      "season": ["Rabi"],
      "soilType": ["Loamy"],
      "waterRequirement": "Low",
      "temperatureRange": "10-25°C",
      "growthDurationDays": 110,
      "fertilizer": "Nitrogen",
      "region": ["Rajasthan", "UP"],
      "pricePerQuintal": 5000,
      "description": "Mustard is used for oil production.",
      "imageUrl": "https://picsum.photos/200?8",
      "searchKeywords": ["mustard", "sarson"]
    },
    {
      "name": "Cotton",
      "nameHindi": "कपास",
      "season": ["Kharif"],
      "soilType": ["Black"],
      "waterRequirement": "Medium",
      "temperatureRange": "21-30°C",
      "growthDurationDays": 180,
      "fertilizer": "Phosphorus",
      "region": ["Gujarat"],
      "pricePerQuintal": 6000,
      "description": "Cotton is used in textile industry.",
      "imageUrl": "https://picsum.photos/200?9",
      "searchKeywords": ["cotton", "kapas"]
    },
    {
      "name": "Barley",
      "nameHindi": "जौ",
      "season": ["Rabi"],
      "soilType": ["Loamy"],
      "waterRequirement": "Low",
      "temperatureRange": "12-25°C",
      "growthDurationDays": 100,
      "fertilizer": "Nitrogen",
      "region": ["UP"],
      "pricePerQuintal": 1800,
      "description": "Barley is used in beverages and food.",
      "imageUrl": "https://picsum.photos/200?10",
      "searchKeywords": ["barley", "jau"]
    },
    {
      "name": "Soybean",
      "nameHindi": "सोयाबीन",
      "season": ["Kharif"],
      "soilType": ["Black"],
      "waterRequirement": "Medium",
      "temperatureRange": "20-30°C",
      "growthDurationDays": 100,
      "fertilizer": "Phosphorus",
      "region": ["MP"],
      "pricePerQuintal": 4000,
      "description": "Soybean is rich in protein.",
      "imageUrl": "https://picsum.photos/200?11",
      "searchKeywords": ["soybean"]
    },
    {
      "name": "Groundnut",
      "nameHindi": "मूंगफली",
      "season": ["Kharif"],
      "soilType": ["Sandy"],
      "waterRequirement": "Low",
      "temperatureRange": "20-30°C",
      "growthDurationDays": 120,
      "fertilizer": "Calcium",
      "region": ["Gujarat"],
      "pricePerQuintal": 4500,
      "description": "Groundnut is used for oil extraction.",
      "imageUrl": "https://picsum.photos/200?12",
      "searchKeywords": ["groundnut", "mungfali"]
    },
    {
      "name": "Chickpea",
      "nameHindi": "चना",
      "season": ["Rabi"],
      "soilType": ["Loamy"],
      "waterRequirement": "Low",
      "temperatureRange": "10-25°C",
      "growthDurationDays": 110,
      "fertilizer": "Phosphorus",
      "region": ["MP", "UP"],
      "pricePerQuintal": 5200,
      "description": "Chickpea is a major pulse crop.",
      "imageUrl": "https://picsum.photos/200?13",
      "searchKeywords": ["chana", "chickpea"]
    },
    {
      "name": "Lentil",
      "nameHindi": "मसूर",
      "season": ["Rabi"],
      "soilType": ["Loamy"],
      "waterRequirement": "Low",
      "temperatureRange": "10-25°C",
      "growthDurationDays": 100,
      "fertilizer": "Organic",
      "region": ["UP", "Bihar"],
      "pricePerQuintal": 5500,
      "description": "Lentil is rich in protein and nutrients.",
      "imageUrl": "https://picsum.photos/200?14",
      "searchKeywords": ["masoor", "lentil"]
    },
    {
      "name": "Bajra",
      "nameHindi": "बाजरा",
      "season": ["Kharif"],
      "soilType": ["Sandy"],
      "waterRequirement": "Low",
      "temperatureRange": "25-35°C",
      "growthDurationDays": 80,
      "fertilizer": "Nitrogen",
      "region": ["Rajasthan"],
      "pricePerQuintal": 2500,
      "description": "Bajra is a drought-resistant crop.",
      "imageUrl": "https://picsum.photos/200?15",
      "searchKeywords": ["bajra"]
    },
  ];
}